### ISSUE TITLE
Generate Swift class using JSON Schema

### ISSUE THREAD

**Issue by dagrooms52** [kylef/JSONSchema.swift#16]
Feature Request:

I can't seem to find a library that will generate Swift classes from JSON schema yet. If you were to implement this feature it would set your project apart from the other JSON schema validators out there.

**Comment by SPopenko** [comment]
@dagrooms52 I believe this could be a good PR for this project in case somebody find time to do this ;)

**Comment by kylef** [comment]
This isn't really in the scope of this library. This project is a **library** is for validating a JSON Schema, it's not a **application** that would do code-generation.

This would be better suited as a completely separate tool than to be included in this library.

If you're planning to build such a tool, I'd recommend not making it Swift specific and allowing users to plug in their own templates so they can use the application to code generate for any language.

There are a couple of existing projects, but unfortunately they are specific to a certain language:

- https://github.com/maxlinc/json-schema-generator
- https://github.com/VoxSupplyChain/json-schema-codegen
