### ISSUE TITLE
Swift 4 & Xcode 9.2 incompatibility

### ISSUE THREAD

**Issue by andylamp** [kylef/JSONSchema.swift#27]
It seems that this is not compatible with the default versions of Swift included from Xcode 9.2 onwards -- gives all sorts of errors. Any plans for a fix?

**Comment by kylef** [comment]
This has been resolved for some time, I'm going to close it as we've already dripped support for Swift 4. JSONSchema.swift 0.5.0 supports Swift 4.2 and onwards
