### ISSUE TITLE
Excess properties in invalid ValidationResult

### ISSUE THREAD

**Issue by djdirtycake** [kylef/JSONSchema.swift#61]
Hello.
Don't know if it's intended or not, but invalid validation result contains all the properties on the same level, not only missing ones.

Here's an example (both 0.5.0 release and latest commit 2f0facb71ceaff3f4b7584e78b3b143afd56485a):

`validate(["price": 34.99, "name": "test"], schema: ["required": ["price", "name", "id"]])`
▿ ValidationResult
  ▿ invalid : 1 element
    - 0 : "Required properties are missing \'[\"price\", \"name\", \"id\"]\'"

**Comment by kylef** [comment]
That looks like a bug, thank you for reporting it. https://github.com/kylef/JSONSchema.swift/commit/c065b6ef33a67dfd539ec9eeae38699e4f6dbadc incorporates a fix for this error.
